-- MySQL Script generated by MySQL Workbench
-- Sat Mar 30 00:45:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Meal_Planner
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Meal_Planner` ;

-- -----------------------------------------------------
-- Schema Meal_Planner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Meal_Planner` DEFAULT CHARACTER SET utf8 ;
USE `Meal_Planner` ;

-- -----------------------------------------------------
-- Table `Meal_Planner`.`origin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`origin` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`origin` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`recipe` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`recipe` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `date_created` DATE NOT NULL,
  `date_last_modified` DATE NOT NULL,
  `thumbnail_id` VARCHAR(36) NULL,
  `author_id` VARCHAR(36) NULL,
  `origin_id` VARCHAR(36) NULL,
  `prep_time` INT(10) NOT NULL DEFAULT 0,
  `cook_time` INT(10) NOT NULL DEFAULT 0,
  `description` TEXT NULL,
  `instruction` JSON NOT NULL,
  `like_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `difficulty` TINYINT NULL,
  `is_deleted` BIT(1) NOT NULL DEFAULT 0,
  `is_archived` BIT(1) NOT NULL DEFAULT 0,
  `is_variant` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_recipe_origin1_idx` (`origin_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_origin1`
    FOREIGN KEY (`origin_id`)
    REFERENCES `Meal_Planner`.`origin` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`ingredient` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`category` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`category` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`recipe_use_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`recipe_use_ingredient` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`recipe_use_ingredient` (
  `recipe_id` VARCHAR(36) NOT NULL,
  `ingredient_id` VARCHAR(36) NOT NULL,
  `amount` SMALLINT NOT NULL,
  `unit` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`recipe_id`, `ingredient_id`),
  INDEX `fk_recipe_has_ingredient_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_recipe_has_ingredient_recipe_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_has_ingredient_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Meal_Planner`.`recipe` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipe_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `Meal_Planner`.`ingredient` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`tag` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`tag` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`recipe_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`recipe_has_tag` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`recipe_has_tag` (
  `recipe_id` VARCHAR(36) NOT NULL,
  `tag_id` BIGINT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`recipe_id`, `tag_id`),
  INDEX `fk_recipe_has_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_recipe_has_tag_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_has_tag_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `Meal_Planner`.`recipe` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipe_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `Meal_Planner`.`tag` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Meal_Planner`.`ingredient_in_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Meal_Planner`.`ingredient_in_category` ;

CREATE TABLE IF NOT EXISTS `Meal_Planner`.`ingredient_in_category` (
  `ingredient_id` VARCHAR(36) NOT NULL,
  `category_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ingredient_id`, `category_id`),
  INDEX `fk_ingredient_has_category_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_ingredient_has_category_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_has_category_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `Meal_Planner`.`ingredient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ingredient_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Meal_Planner`.`category` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
